spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:finance}}
spring.datasource.username=${DB_USERNAME:${POSTGRES_USER:finance}}
spring.datasource.password=${DB_PASSWORD:${POSTGRES_PASSWORD:finance}}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
